name: lim
description: A set of maximum and minimum constant values for Dart datatypes and character codes.
version: 0.1.6
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/lim/

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
