name: lim
description: A set of maximum and minimum constant values for Dart datatypes and character codes.
version: 0.1.2
homepage: https://github.com/aiurovet/lim/

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
